name: Penny Wang
description: Front-End Developer • React • UX/UI Design
url: "https://pwang8888.github.io"
baseurl: ""
avatar: images/avatar.jpg # (Optional: add a photo)

# Social links (optional)
github_username: pwang8888
twitter_username: your_twitter
